In [11]:
import numpy as np
import pandas as pd
import xgboost as xgb

from sklearn.metrics import accuracy_score
from sklearn.model_selection import train_test_split
import matplotlib.pyplot as plt


In [12]:
index=np.arange(1,8)
cgpa= np.array([[9.9,95],[5.1,70],[6.5,80],[8.0,95],[7.5,85],[8.5,80],[9.5,95],[7.9,70],[9.0,95],[7.5,86]])

In [13]:
package = np.array([4.5,10.0,15.0,25.0,12.0,8.0,30.0,5.0,7.0,8.0])

In [14]:
place=pd.DataFrame()
# place

In [15]:
x_train, x_test, y_train, y_test = train_test_split(cgpa,package,test_size=7,random_state=0)


In [16]:
xgb_train = xgb.DMatrix(x_train,y_train,enable_categorical= True)

xgb_test= xgb.DMatrix(x_test, y_test,enable_categorical=True)

In [17]:
# xgb_r = xgb.XGBRegressor(objective ='reg:linear', 
                # n_estimators = 5000,   seed = 123) 

In [47]:
param = {"booster":"gblinear", "objective":"reg:linear"} 
  
xgb_r = xgb.train(params = param, dtrain = xgb_train, num_boost_round = 50)
pred = xgb_r.predict(xgb_test) 


C:\Users\choud\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\xgboost\core.py:158: UserWarning: [18:00:28] WARNING: C:\buildkite-agent\builds\buildkite-windows-cpu-autoscaling-group-i-0015a694724fa8361-1\xgboost\xgboost-ci-windows\src\objective\regression_obj.cu:227: reg:linear is now deprecated in favor of reg:squarederror.
  warnings.warn(smsg, UserWarning)


In [48]:
# xgb_r.fit(x_train,y_train)
# y_pred=xgb_r.predict(x_test)

In [49]:
from sklearn.metrics import mean_squared_error as MSE 

rmse = np.sqrt(MSE(y_test, pred)) 
print("RMSE : % f" %(rmse))


RMSE :  8.142277


In [50]:
# accuracy_score(y_pred,y_test)

In [51]:
pred , y_test

(array([14.779666, 12.861324, 13.863738, 14.012329, 15.616192, 12.031883,
        10.971319], dtype=float32),
 array([15.,  7., 12.,  8., 10., 30.,  5.]))

In [52]:
pred , y_test

(array([14.779666, 12.861324, 13.863738, 14.012329, 15.616192, 12.031883,
        10.971319], dtype=float32),
 array([15.,  7., 12.,  8., 10., 30.,  5.]))